FROM golang:1.19.4 as builder

WORKDIR /src/
COPY . .

RUN go build -o /app/webapi ./cmd/webapi

FROM debian:bullseye

EXPOSE 3000 4000

WORKDIR /app/
RUN mkdir -p -m a=rwx ./service/database/
COPY --from=builder /app/webapi ./

CMD ["/app/webapi"]
